# 图像分类原理
## 感知机
## 全连接层
## 卷积神经网络
### Imagenet
### VGG
* 证明了随着模型深度的增加，模型效果越好
* 使用较小的3x3的卷积，代替了alexnet中的11x11,7x7以及5x5的大卷积核
  * 将5x5的卷积用2层3x3的卷积替换，将7x7的卷积用3层3x3的卷积替换，减少了网络参数
  * 在相同感受野的情况下，加深了网络参数，从而提取更多非线性的信息
### GoogLeNet
* 以不同尺度的卷积来提取不同的特征
* inception模块
  * ![](images/image-classification-2022-10-03-20-40-46.png)
### ResNet
* 网络退化问题
  * 当一个网络可以开始收敛时，随着网络层数的增加，网络的精度逐渐达到饱和，并且会迅速降低。这里精度降低的原因并不是过拟合造成的
  * 假设 20 层是一个最优的网络，通过加深到 56 层之后，理论上后面的 36 层是可以通过学习到一个恒等映射的，也就是说理论上不会学习到一个比 26 层还差的网络。所以，作者猜测网络不能很容易地学习到恒等映射 (恒等映射就是 f(x)=x)
* 残差学习
  * 因为网络不容易学习到恒等映射，所以就让它强制添加一个恒等映射
  * ![](images/image-classification-2022-10-03-20-52-01.png)



In [2]:
## softmax

import torch
import torch.nn as nn

y=torch.randn(2)
print(y)
m=nn.Softmax(dim=0)
out=m(y)
print(out)

tensor([-0.0991, -0.7567])
tensor([0.6587, 0.3413])


In [3]:
x= torch.randint(0,255,(1,128*128),dtype=torch.float32)
fc = nn.Linear(128*128,2)
y=fc(x)
print(y)

output = nn.Softmax(dim=1)(y)
print(output)

tensor([[-3.1655, -6.3710]], grad_fn=<AddmmBackward0>)
tensor([[0.9610, 0.0390]], grad_fn=<SoftmaxBackward0>)
